### PR TITLE
Fix a few warnings

### PR DESCRIPTION
**Pull request by thilinarmtb**
Fixed a few warnings I encountered while building. No major changes. 
Tests pass locally.

@solomonik : Please have a look.

### CODE REVIEW

**Comment by solomonik** [comment]
Looks good, thanks!

**Comment by thilinarmtb** [comment]
Thanks for merging !!!

**Comment by solomonik** [comment]
No problem.  By the way, in case you ran into this problem, someone just told me today that the doxygen links were broken.  They are fixed as of this afternoon.  The bulk of the documentation is there.

**Comment by thilinarmtb** [comment]
Yes, they were broken. Now they are accessible. Thanks !!

**Pull request merged**
