### PR TITLE
detect Mac math library

### PR DESCRIPTION
**Pull request by jeffhammond**

### CODE REVIEW

**Comment by devinamatthews** [comment]
As far as I know, the default -lblas on Mac is the same as -framework 
Accelerate. Is a separate check necessary?

**Comment by jeffhammond** [comment]
I don't have see `libblas.*` in `/usr`.  It would be profoundly evil if Apple were to have the linker translate `-lblas` to `-framework Accelerate`, given that it would break any project that assumes `libblas.*` is something else (e.g. a library of Basic Linguistic Analysis Software 😃 ).

I see there is a `libBLAS.dylib` deep in the bowels of the Mac framework complex, but it is seems odd to me that it is used by default, for the reasons noted above.
```
jrhammon-mac01:src-mpi-pr jrhammon$ ldd /System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/vecLib
/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/vecLib:
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib (compatibility version 1.0.0, current version 563.5.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib (compatibility version 1.0.0, current version 563.5.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib (compatibility version 1.0.0, current version 563.5.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLinearAlgebra.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

**Comment by devinamatthews** [comment]
[dmatthews@Devin's iMac eomdip]$ls -l /usr/lib/libblas.dylib
lrwxr-xr-x  1 root  wheel  116 Dec  9  2015 /usr/lib/libblas.dylib -> 
../../System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib

**Comment by jeffhammond** [comment]
I blame my inability to use `find` correctly the first time on undercaffeination.  You are right.  This feature is not necessary.

**Pull request closed without merging**
