### PR TITLE
Enhancements for configure

### PR DESCRIPTION
**Pull request by devinamatthews**
1) I changed the test for the __APPLE__ macro to a compile-only check using #error, which is slightly friendlier than actually running the compiled program.

2) I added out-of-tree build capability. For example:

git checkout ... ctf
mkdir build
cd build
../ctf/configure
make

I tested that everything still works in-tree as well.

### CODE REVIEW

**Comment by solomonik** [comment]
Hi Devin,

What is the point of determining a src directory at configure time?  I like
being able to change the name or move the source directory without breaking
the build inside of it, so from this perspective I prefer just doing
everything with relative paths.

Thanks,
Edgar

**Comment by solomonik** [comment]
Ok I understand the feature now and its good.  However, it seems like having a $(BUILDDIR) in front of all the object files and the path to config.mk in the Makefiles would allow multiple builds to share the regular Makefile tree without copying it over (each could have a single Makefile that sets a $BUILDIR) and would allow for no $SRCDIR as well as proper support of relative build paths.

**Comment by devinamatthews** [comment]
The "usual" way (as far as such a thing is standardized) is to have a single source tree and then make multiple build trees wherever for each build configuration, where each build tree has a distinct path and its own Makefiles, object files, etc.  True you could do it so that you create and manage "remote" build trees from the central src dir, but that is not the way I've done it so I went with what I know. I think this way (what I wrote) would also be more familiar to new users since it is what autoconf does.

Re: relative $SRCDIR: this could be supported by keeping the initial path to the srcdir as determined by $0 in configure, then only using the "canonicalized" $SRCDIR as determined by `cd $srcdir;pwd` for comparing with $builddir. I can implement this if you'd like.

**Comment by solomonik** [comment]
OK, well I kind of consider Makesfiles to be a part of the source and don't
think they should be copied. I agree that a commonality of build systems is
constructing separate object trees and this makes sense, but I've seen them
do it without copying the Makefiles. And also I made an effort to remove
the notion of a srcdir from CTF and don't really want it reintroduced, even
if there are working around (I don't fully understand yours yet). I can
implement this in the way I am proposing if you don't want to.

Edgar

**Comment by devinamatthews** [comment]
OK, I just wanted a way to simultaneously build debug/release + gcc/intel from the same source tree. If you would rather accomplish that some other way please do.

**Comment by devinamatthews** [comment]
And FWIW the Makefiles are linked so changes in the src dir are reflected. Adding new Makefiles would have to be handled by moving the link_makefiles function into the root Makefile with proper dependencies.

**Comment by solomonik** [comment]
Ok, I implemented what I previously proposed and pushed it to
origin/manybuilds.  Please check that it works for you and integrate with
the other changes (i.e. APPLE macro check).

Thanks,
Edgar

**Comment by devinamatthews** [comment]
I'll close this request and open a new one in the manybuilds branch.

**Pull request closed without merging**
